export const teams = 
    [
        { 
        name: "Illarion",
        surName: "Ulanov",
        position: "Team-lead",
        git: "https://github.com/Larik7",
        linkedin: "https://www.linkedin.com/",
        description: ["Building the project architecture, calendar, developing the project backend and frontend"],
        avatar: require('../../../../images/team/Уланов_Ілларіон.jpg'),
        },
        { 
        name: "Vladimir",
        surName: "Plotnikov",
        position: "Scrum-master",
        git: "https://github.com/",
        linkedin: "https://www.linkedin.com/",
        description: ["Organization of teamwork"],
        avatar: require('../../../../images/team/Владимир_Плотников.jpg'),
       },
       { 
        name: "Anatoliy",
        surName: "Dubey",
        position: "Developer",
        git: "https://github.com/DubeiA",
        linkedin: "https://www.linkedin.com/",
        description: ["Development of a user registration block, сalendar development"],
        avatar: require('../../../../images/team/Дубей_Анатолій.jpg'),
       },
       { 
        name: "Andrey",
        surName: "Muzika",
        position: "Developer",
        git: "https://github.com/Ahamoth",
        linkedin: "https://www.linkedin.com/",
        description: ["Development of the backend of registration, login and avatar blocks. Swagger"],
        avatar: require('../../../../images/team/Музыка_Андрей.jpg'),
       },
       { 
        name: "Anton",
        surName: "Zvertanovskiy",
        position: "Developer",
        git: "https://github.com/internet-user-0",
        linkedin: "https://www.linkedin.com/",
        description: ["Calendar and tasks development"],
        avatar: require('../../../../images/team/Антон_Звертановський.jpg'),
       },
       { 
        name: "Larisa",
        surName: "Melnichenko",
        position: "Developer",
        git: "https://github.com/Erlara",
        linkedin: "https://www.linkedin.com/",
        description: ["Development of a block of statistics"],
        avatar: require('../../../../images/team/Мельниченко_Лариса.jpg'),
       },
       { 
        name: "Anton",
        surName: "Logvinenko",
        position: "Developer",
        git: "https://github.com/Anton-Logvinenko",
        linkedin: "https://www.linkedin.com/",
        description:[ "LoginPage development"],
        avatar: require('../../../../images/team/Антон_Логвиненко.jpg'),
       },
       { 
        name: "Denis",
        surName: "Baydin",
        position: "Developer",
        git: "https://github.com/Trancendence",
        linkedin: "https://www.linkedin.com/",
        description: ["Development of a slider with reviews and a modal window with information about the team"],
        avatar: require('../../../../images/team/Байдін_Денис.jpg'),
       },
       { 
        name: "Valeriya",
        surName: "Frolova",
        position: "Developer",
        git: "https://github.com/Valeriia2306",
        linkedin: "https://www.linkedin.com/",
        description:[ "Development of a modal window with reviews"],
        avatar: require('../../../../images/team/Фролова_Валерія.jpg'),
       },
       { 
        name: "Maxim",
        surName: "Stankov",
        position: "Developer",
        git: "https://github.com/Demiurge232",
        linkedin: "https://www.linkedin.com/",
        description: ["Calendar and tasks development"],
        avatar: require('../../../../images/team/Станков_Максим.jpg'),
        },
        { 
        name: "Andrey",
        surName: "Marchuk",
        position: "Developer",
        git: "https://github.com/Demiurge232",
        linkedin: "https://www.linkedin.com/",
        description: ["Calendar and tasks development"],
        avatar: require('../../../../images/team/Марчук_Андрій.jpg'),
        },
       { 
        name: "Dmitriy",
        surName: "Zgovnovskiy",
        position: "Developer",
        git: "https://github.com/zhdima",
        linkedin: "https://www.linkedin.com/",
        description: ["Development of the backend of reviews and tasks. Swagger"],
        avatar: require('../../../../images/team/Жовновський_Дмитро.jpg'),
       },
       { 
        name: "Anastasiya",
        surName: "Shamalo",
        position: "Developer",
        git: "https://github.com/",
        linkedin: "https://www.linkedin.com/in/",
        description: ["Development of sidebar and header modules"],
        avatar: require('../../../../images/team/Анастасия_Шамало.jpg'),
        },
       { 
        name: "Pavlo",
        surName: "Ziuskin",
        position: "Developer",
        git: "https://github.com/PavloZiuskin",
        linkedin: "https://www.linkedin.com/in/",
        description: ["Development of User Profile"],
        avatar: require('../../../../images/team/Павло_Зюськин.jpg'),
        },
    ];
 